version: 2
jobs:
  build:
    machine:
      environment:
        image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: install awscli
          command: ./.circleci/deploy.sh
